language: node_js
node_js:
  #  - stable
  - "12"
sudo: false
git:
  depth: 1
install:
  - npm ci
cache:
  directories:
    - "$HOME/.npm"
script:
  - npm run lint
#  - npm run test
  - npm run build

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
  on:
    tags: false
    all_branches: true

env:
  global:

